name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # 4. Сборка и экспорт Next.js
      - name: Build Next.js
        run: npm run build


      # 5. Копируем mockServiceWorker.js в подпапку с названием репозитория
      - name: Add mockServiceWorker.js
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          mkdir -p out/$REPO_NAME
          if [ -f public/mockServiceWorker.js ]; then
            cp public/mockServiceWorker.js out/$REPO_NAME/
          fi
          touch out/.nojekyll

      # 6. Проверяем содержимое out (опционально)
      - name: List out folder
        run: ls -R out

      # 7. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out        # содержимое out в корень
          user_name: yaroslavskiba
          user_email: yaroslavskiba322@gmail.com
          force_orphan: true

